#!/usr/bin/env python3
import argparse
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import yaml

HTTP_SCHEMES = ("http://", "https://")
METHOD_ORDER = ["get", "post", "put", "patch", "delete", "options", "head", "trace"]
DEPRECATED_FLAGS = [
    "deprecated",
    "x-deprecated",
    "x-deprecated-operation",
    "x-legacy-deprecated",
    "x-deprecated-endpoint",
]
GENERATED_MARKER = "<!-- Generated by tools/generate_openapi_docs.py -->"
ENDPOINT_LINE_PREFIXES = ("- ", "* ")


def slugify(value: str) -> str:
    out = []
    prev_dash = False
    for ch in value.lower():
        if ch.isalnum():
            out.append(ch)
            prev_dash = False
        else:
            if not prev_dash:
                out.append("-")
                prev_dash = True
    slug = "".join(out).strip("-")
    return slug or "spec"


def read_text_from_url(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "PropAir-OpenAPI-DocGen"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def load_spec(spec_ref: str, base_dir: Path) -> Dict[str, Any]:
    if spec_ref.startswith(HTTP_SCHEMES):
        validate_remote_url(spec_ref)
        raw = read_text_from_url(spec_ref)
    else:
        raw = (base_dir / spec_ref).read_text(encoding="utf-8")

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        data = yaml.safe_load(raw)
        if not isinstance(data, dict):
            raise ValueError("OpenAPI spec did not parse to an object")
        return data


def parse_endpoints_from_markdown(markdown_path: Path) -> List[Dict[str, Any]]:
    if not markdown_path.exists():
        raise ValueError(f"Markdown file not found for endpoint allowlist: {markdown_path}")

    lines = markdown_path.read_text(encoding="utf-8").splitlines()
    in_endpoints = False
    include_paths: List[Dict[str, Any]] = []

    for raw in lines:
        line = raw.strip()
        if line.startswith("## "):
            in_endpoints = line.lower().startswith("## endpoints")
            continue
        if not in_endpoints:
            continue
        if line.startswith("## "):
            break
        if not line.startswith(ENDPOINT_LINE_PREFIXES):
            continue

        cleaned = line.lstrip("-* ").strip()
        if not cleaned:
            continue

        parts = cleaned.split()
        if len(parts) < 2:
            continue

        method = parts[0].strip("`").lower()
        path = parts[1].strip("`")
        if not path.startswith("/"):
            continue
        include_paths.append({"path": path, "methods": [method]})

    if not include_paths:
        raise ValueError(f"No endpoints found under '## Endpoints' in {markdown_path}")

    return include_paths


def openapi_from_markdown(
    name: str,
    include_paths: List[Dict[str, Any]],
    servers: List[str],
) -> Dict[str, Any]:
    if not include_paths:
        raise ValueError(f"No endpoints supplied for markdown-only OpenAPI: {name}")

    openapi_paths: Dict[str, Dict[str, Any]] = {}
    for item in include_paths:
        path = item.get("path")
        if not path:
            continue
        methods = item.get("methods") or []
        for method in methods:
            method_lower = method.lower()
            op = {
                "operationId": operation_id_fallback(method_lower, path),
                "responses": {
                    "200": {"description": "Successful response"},
                },
            }
            openapi_paths.setdefault(path, {})[method_lower] = op

    openapi = {
        "openapi": "3.0.3",
        "info": {
            "title": f"{name} API",
            "version": "unknown",
        },
        "paths": {k: openapi_paths[k] for k in sorted(openapi_paths.keys())},
    }

    if servers:
        openapi["servers"] = [{"url": url} for url in servers]

    return openapi


def normalize_path_template(path: str) -> str:
    out = []
    in_param = False
    for ch in path:
        if ch == "{":
            in_param = True
            out.append("{")
            continue
        if ch == "}":
            in_param = False
            out.append("}")
            continue
        if in_param:
            continue
        out.append(ch)
    return "".join(out)


def filter_openapi_paths(
    spec: Dict[str, Any],
    include_paths: List[Dict[str, Any]],
) -> Dict[str, Any]:
    if not include_paths:
        return spec

    allowed: Dict[str, List[str]] = {}
    for item in include_paths:
        path = item.get("path")
        if not path:
            continue
        methods = [m.lower() for m in (item.get("methods") or [])]
        allowed[path] = methods

    paths = spec.get("paths") or {}
    if not isinstance(paths, dict):
        return spec

    filtered_paths: Dict[str, Dict[str, Any]] = {}
    allowed_norm = {
        normalize_path_template(path): methods for path, methods in allowed.items()
    }

    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        norm = normalize_path_template(path)
        if norm not in allowed_norm:
            continue
        allowed_methods = allowed_norm[norm]
        kept: Dict[str, Any] = {}
        for method, op in path_item.items():
            if not isinstance(op, dict):
                continue
            if allowed_methods and method.lower() not in allowed_methods:
                continue
            kept[method] = op
        if kept:
            filtered_paths[path] = kept

    spec["paths"] = {k: filtered_paths[k] for k in sorted(filtered_paths.keys())}
    return spec


def discovery_to_openapi(
    discovery: Dict[str, Any],
    include_paths: List[Dict[str, Any]],
) -> Dict[str, Any]:
    if not isinstance(discovery, dict):
        raise ValueError("Discovery document did not parse to an object")

    title = discovery.get("title") or "Google API"
    version = discovery.get("version") or "unknown"
    root_url = discovery.get("rootUrl") or ""
    service_path = discovery.get("servicePath") or ""
    base_url = discovery.get("baseUrl") or f"{root_url}{service_path}"
    base_url = base_url.rstrip("/") + "/" if base_url else ""

    schema_defs = discovery.get("schemas") or {}
    resources = discovery.get("resources") or {}
    methods = discovery.get("methods") or {}

    def collect_methods(resource_block: Dict[str, Any]) -> List[Dict[str, Any]]:
        collected = []
        for method in resource_block.get("methods", {}).values():
            if isinstance(method, dict):
                collected.append(method)
        for child in resource_block.get("resources", {}).values():
            if isinstance(child, dict):
                collected.extend(collect_methods(child))
        return collected

    all_methods = list(methods.values())
    for resource in resources.values():
        if isinstance(resource, dict):
            all_methods.extend(collect_methods(resource))

    include_lookup: Dict[str, List[str]] = {}
    for item in include_paths:
        path = item.get("path")
        if not path:
            continue
        methods_list = item.get("methods") or []
        include_lookup[path] = [m.lower() for m in methods_list]

    paths: Dict[str, Dict[str, Any]] = {}
    used_schemas: Dict[str, Any] = {}

    def add_schema_ref(ref: Optional[str]) -> Optional[Dict[str, Any]]:
        if not ref:
            return None
        if ref in schema_defs and ref not in used_schemas:
            used_schemas[ref] = schema_defs[ref]
        return {"$ref": f"#/components/schemas/{ref}"}

    for method in all_methods:
        path = method.get("path")
        http_method = (method.get("httpMethod") or "").lower()
        if not path or not http_method:
            continue
        if path not in include_lookup:
            continue
        allowed_methods = include_lookup[path]
        if allowed_methods and http_method not in allowed_methods:
            continue

        operation: Dict[str, Any] = {
            "operationId": method.get("id") or method.get("methodId") or f"{http_method}_{path}",
            "summary": method.get("description") or method.get("summary") or "",
        }

        params = []
        for name, param in sorted((method.get("parameters") or {}).items()):
            if not isinstance(param, dict):
                continue
            location = param.get("location") or "query"
            schema = {}
            if param.get("type"):
                schema["type"] = param.get("type")
            if param.get("format"):
                schema["format"] = param.get("format")
            if param.get("enum"):
                schema["enum"] = param.get("enum")
            param_entry = {
                "name": name,
                "in": location,
                "required": bool(param.get("required")),
                "description": param.get("description") or "",
                "schema": schema or {"type": "string"},
            }
            params.append(param_entry)

        if params:
            operation["parameters"] = params

        request_ref = None
        if isinstance(method.get("request"), dict):
            request_ref = method["request"].get("$ref")
        request_schema = add_schema_ref(request_ref)
        if request_schema:
            operation["requestBody"] = {
                "content": {
                    "application/json": {
                        "schema": request_schema,
                    }
                }
            }

        response_ref = None
        if isinstance(method.get("response"), dict):
            response_ref = method["response"].get("$ref")
        response_schema = add_schema_ref(response_ref)
        responses: Dict[str, Any] = {}
        responses["200"] = {
            "description": "Successful response",
        }
        if response_schema:
            responses["200"]["content"] = {
                "application/json": {
                    "schema": response_schema,
                }
            }
        operation["responses"] = responses

        paths.setdefault(path, {})[http_method] = operation

    openapi = {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": version,
        },
        "servers": [{"url": base_url}] if base_url else [],
        "paths": {k: paths[k] for k in sorted(paths.keys())},
    }

    if used_schemas:
        openapi["components"] = {"schemas": used_schemas}

    return openapi


def validate_remote_url(url: str) -> None:
    if "raw.githubusercontent.com" in url:
        if "/main/" in url or "/master/" in url or "/refs/heads/" in url:
            raise ValueError(f"Remote spec URL must be pinned to a tag or commit: {url}")


def is_deprecated(operation: Dict[str, Any]) -> bool:
    for key in DEPRECATED_FLAGS:
        if operation.get(key):
            return True
    return False


def merge_parameters(path_params: List[Dict[str, Any]], op_params: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    merged: Dict[Tuple[str, str], Dict[str, Any]] = {}
    for param in path_params:
        key = (param.get("name", ""), param.get("in", ""))
        merged[key] = param
    for param in op_params:
        key = (param.get("name", ""), param.get("in", ""))
        merged[key] = param
    return sorted(merged.values(), key=lambda p: (p.get("in", ""), p.get("name", "")))


def extract_security(operation: Dict[str, Any], spec: Dict[str, Any]) -> List[str]:
    security = operation.get("security")
    if security is None:
        security = spec.get("security")
    if security == []:
        return []
    if not security:
        return []
    schemes: List[str] = []
    for item in security:
        if isinstance(item, dict):
            for key in item.keys():
                if key not in schemes:
                    schemes.append(key)
    return schemes


def extract_content_types(request_body: Any) -> List[str]:
    if not request_body or not isinstance(request_body, dict):
        return []
    content = request_body.get("content")
    if not isinstance(content, dict):
        return []
    return sorted(content.keys())


def extract_response_content_types(responses: Any) -> Dict[str, List[str]]:
    out: Dict[str, List[str]] = {}
    if not isinstance(responses, dict):
        return out
    for code, resp in responses.items():
        if not isinstance(resp, dict):
            continue
        content = resp.get("content")
        if isinstance(content, dict):
            out[str(code)] = sorted(content.keys())
        else:
            out[str(code)] = []
    return out


def response_sort_key(code: str) -> Tuple[int, int, str]:
    if code == "default":
        return (2, 0, code)
    try:
        return (0, int(code), code)
    except ValueError:
        return (1, 0, code)


def format_metadata_line(
    operation_id: str,
    method: str,
    path: str,
    auth_schemes: List[str],
    content_types: List[str],
    response_types: List[str],
    tags: List[str],
) -> str:
    auth = "none" if not auth_schemes else ",".join(auth_schemes)
    req_ct = "none" if not content_types else ",".join(content_types)
    resp_ct = "none" if not response_types else ",".join(response_types)
    tags_value = "none" if not tags else ",".join(tags)
    return (
        f"`@endpoint {operation_id} @method {method.upper()} @path {path} "
        f"@auth {auth} @content-type {req_ct} @response-content-type {resp_ct} @tags {tags_value}`"
    )


def iter_operations(spec: Dict[str, Any]) -> Iterable[Tuple[str, str, Dict[str, Any], Dict[str, Any]]]:
    paths = spec.get("paths") or {}
    if not isinstance(paths, dict):
        return
    for path in sorted(paths.keys()):
        path_item = paths.get(path) or {}
        if not isinstance(path_item, dict):
            continue
        path_params = path_item.get("parameters") or []
        for method in METHOD_ORDER:
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            if is_deprecated(operation):
                continue
            yield path, method, operation, {"path_params": path_params}


def operation_id_fallback(method: str, path: str) -> str:
    return slugify(f"{method}-{path}")


def generate_markdown(spec: Dict[str, Any], spec_ref: str, name: str) -> str:
    info = spec.get("info") or {}
    title = info.get("title") or name
    version = info.get("version") or "unknown"
    openapi_version = spec.get("openapi") or spec.get("swagger") or "unknown"

    servers = []
    for server in spec.get("servers") or []:
        if isinstance(server, dict) and server.get("url"):
            servers.append(server["url"])
    servers = sorted(set(servers))

    lines: List[str] = []
    lines.append(GENERATED_MARKER)
    lines.append(f"# {title} API (Generated)")
    lines.append("")
    lines.append(f"Source: `{spec_ref}`")
    lines.append(f"OpenAPI: `{openapi_version}`")
    lines.append(f"Version: `{version}`")
    if servers:
        lines.append("Base URLs:")
        for url in servers:
            lines.append(f"- `{url}`")
    lines.append("")
    lines.append("## Endpoints")
    lines.append("")

    for path, method, operation, context in iter_operations(spec):
        operation_id = operation.get("operationId") or operation_id_fallback(method, path)
        summary = operation.get("summary") or ""
        description = operation.get("description") or ""
        tags = sorted(set(operation.get("tags") or []))
        auth_schemes = extract_security(operation, spec)

        path_params = context.get("path_params") or []
        op_params = operation.get("parameters") or []
        params = merge_parameters(path_params, op_params)

        request_body = operation.get("requestBody")
        content_types = extract_content_types(request_body)

        responses = operation.get("responses") or {}
        response_types_map = extract_response_content_types(responses)
        response_content_types = sorted(
            {ct for types in response_types_map.values() for ct in types}
        )

        lines.append(f"### `{method.upper()} {path}`")
        lines.append(
            format_metadata_line(
                operation_id=operation_id,
                method=method,
                path=path,
                auth_schemes=auth_schemes,
                content_types=content_types,
                response_types=response_content_types,
                tags=tags,
            )
        )
        if summary:
            lines.append("")
            lines.append(f"Summary: {summary}")
        if description:
            lines.append("")
            lines.append("Description:")
            lines.append(description)
        if tags:
            lines.append("")
            lines.append(f"Tags: {', '.join(tags)}")

        if params:
            lines.append("")
            lines.append("Parameters:")
            for param in params:
                name = param.get("name") or "unknown"
                location = param.get("in") or "unknown"
                required = "required" if param.get("required") else "optional"
                schema = param.get("schema") or {}
                ptype = schema.get("type") or "object"
                desc = param.get("description")
                line = f"- `{name}` ({location}, {required}, type: {ptype})"
                if desc:
                    line += f" - {desc}"
                lines.append(line)

        if request_body:
            lines.append("")
            lines.append("Request Body:")
            if isinstance(request_body, dict) and "$ref" in request_body:
                lines.append(f"- `$ref`: `{request_body['$ref']}`")
            else:
                required = "required" if isinstance(request_body, dict) and request_body.get("required") else "optional"
                lines.append(f"- {required}")
                lines.append(
                    f"- content types: {', '.join(content_types) if content_types else 'none'}"
                )

        if responses:
            lines.append("")
            lines.append("Responses:")
            for code in sorted(response_types_map.keys(), key=response_sort_key):
                types = response_types_map.get(code) or []
                types_value = ", ".join(types) if types else "none"
                lines.append(f"- {code}: {types_value}")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_index(
    output_path: Path,
    manifest: Dict[str, Any],
    generated_files: Dict[str, Path],
) -> None:
    lines: List[str] = []
    lines.append("# Generated API References")
    lines.append("")
    lines.append("This index is generated from `openapi-docs.yaml`.")
    lines.append("")

    def render_group(title: str, items: List[Dict[str, Any]], prefix: str) -> None:
        lines.append(f"## {title}")
        lines.append("")
        for item in items:
            name = item.get("name") or item.get("id") or "unknown"
            item_id = slugify(item.get("id") or name)
            status = item.get("status") or "active"
            spec_ref = item.get("spec")
            if status == "manual" or not spec_ref:
                lines.append(f"- {name} (manual)")
                continue
            target = generated_files.get(prefix + item_id)
            if target:
                rel = target.relative_to(output_path.parent).as_posix()
                lines.append(f"- [{name}]({rel})")
            else:
                lines.append(f"- {name} (missing output)")
        lines.append("")

    specs = manifest.get("specs") or {}
    render_group("Sources", specs.get("sources") or [], "sources:")
    render_group("Integrations", specs.get("integrations") or [], "integrations:")

    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def clean_stale_files(output_dir: Path, keep: Iterable[Path]) -> None:
    keep_set = {p.resolve() for p in keep}
    for path in output_dir.glob("*.md"):
        if path.name == ".gitkeep":
            continue
        if path.resolve() not in keep_set:
            try:
                content = path.read_text(encoding="utf-8")
            except OSError:
                continue
            if GENERATED_MARKER in content:
                path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate API docs from OpenAPI specs")
    parser.add_argument("--manifest", default="openapi-docs.yaml")
    args = parser.parse_args()

    manifest_path = Path(args.manifest).resolve()
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(manifest, dict):
        print("Manifest did not parse to an object", file=sys.stderr)
        return 1

    defaults_cfg = manifest.get("defaults") or {}
    output_cfg = manifest.get("output") or {}
    sources_dir = Path(output_cfg.get("sources_dir", "docs/libraries"))
    integrations_dir = Path(output_cfg.get("integrations_dir", "docs/plugins"))
    index_path = Path(output_cfg.get("index", "docs/openapi-generated-index.md"))

    sources_dir.mkdir(parents=True, exist_ok=True)
    integrations_dir.mkdir(parents=True, exist_ok=True)
    index_path.parent.mkdir(parents=True, exist_ok=True)

    generated_files: Dict[str, Path] = {}

    specs = manifest.get("specs") or {}
    for group_name, output_dir in ("sources", sources_dir), ("integrations", integrations_dir):
        items = specs.get(group_name) or []
        for item in items:
            spec_ref = item.get("spec")
            spec_type = item.get("spec_type")
            discovery_url = item.get("discovery_url")
            include_paths = item.get("include_paths")
            status = item.get("status") or "active"
            if status == "manual" or (
                not spec_ref
                and not discovery_url
                and spec_type not in ("discovery", "markdown")
            ):
                continue
            name = item.get("name") or item.get("id") or "unknown"
            item_id = slugify(item.get("id") or name)
            output_name = item.get("output")
            if output_name:
                target = output_dir / output_name
            else:
                target = output_dir / f"{item_id}.md"
            overwrite_default = defaults_cfg.get("overwrite", True)
            if target.exists() and not item.get("overwrite", overwrite_default):
                print(
                    f"Refusing to overwrite existing file without overwrite: true: {target}",
                    file=sys.stderr,
                )
                return 1
            if spec_type == "discovery" or discovery_url:
                if not discovery_url:
                    raise ValueError(f"Missing discovery_url for {name}")
                if include_paths is None:
                    include_paths = parse_endpoints_from_markdown(target)
                discovery = load_spec(str(discovery_url), manifest_path.parent)
                spec = discovery_to_openapi(discovery, include_paths)
                spec_label = f"discovery:{discovery_url}"
            elif spec_type == "markdown":
                if include_paths is None:
                    include_paths = parse_endpoints_from_markdown(target)
                servers = item.get("servers") or []
                spec = openapi_from_markdown(name, include_paths, servers)
                spec_label = "markdown"
            else:
                spec = load_spec(str(spec_ref), manifest_path.parent)
                if include_paths is None:
                    include_paths = parse_endpoints_from_markdown(target)
                spec = filter_openapi_paths(spec, include_paths)
                spec_label = str(spec_ref)
            markdown = generate_markdown(spec, spec_label, name)
            target.write_text(markdown, encoding="utf-8")
            generated_files[f"{group_name}:{item_id}"] = target

    clean_stale_files(sources_dir, generated_files.values())
    clean_stale_files(integrations_dir, generated_files.values())

    write_index(index_path, manifest, generated_files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
